### ISSUE TITLE
ModuleNotFoundError: No module named 'kanapy'

### ISSUE THREAD

**Issue by harris-2374** [EichlerLab/pav#10]
Hi,

I was wondering if I could get some help resolving a bug I keep seeing when running pav. I ran pav on a few assemblies of ours and noticed when the pipeline finished that I was receiving an error in a log file that stopped pav from generating figures (looks like the dot plots). The pipeline was able to complete normally and didn't fail when reaching this error, so I am not sure if this is expected or not. I attached the first entry of one of the log files with the error, let me know if I can provide any other information to help.

Thanks,
Andrew

[inv_call_0.log](https://github.com/EichlerLab/pav/files/8993502/inv_call_0.log)

**Comment by zou-yawen** [comment]
> Hi,
> 
> I was wondering if I could get some help resolving a bug I keep seeing when running pav. I ran pav on a few assemblies of ours and noticed when the pipeline finished that I was receiving an error in a log file that stopped pav from generating figures (looks like the dot plots). The pipeline was able to complete normally and didn't fail when reaching this error, so I am not sure if this is expected or not. I attached the first entry of one of the log files with the error, let me know if I can provide any other information to help.
> 
> Thanks, Andrew
> 
> [inv_call_0.log](https://github.com/EichlerLab/pav/files/8993502/inv_call_0.log)

maybe you can git clone from  https://github.com/paudano/kanapy,it work

**Comment by zou-yawen** [comment]
> Hi,
> 
> I was wondering if I could get some help resolving a bug I keep seeing when running pav. I ran pav on a few assemblies of ours and noticed when the pipeline finished that I was receiving an error in a log file that stopped pav from generating figures (looks like the dot plots). The pipeline was able to complete normally and didn't fail when reaching this error, so I am not sure if this is expected or not. I attached the first entry of one of the log files with the error, let me know if I can provide any other information to help.
> 
> Thanks, Andrew
> 
> [inv_call_0.log](https://github.com/EichlerLab/pav/files/8993502/inv_call_0.log)

maybe you can git clone from https://github.com/paudano/kanapy,  it work

**Comment by paudano** [comment]
Something got out of sync between PAV and its dependencies. If you do a recursive clone (`git clone --recursive https://github.com/EichlerLab/pav.git`), kanapy will come with the svpop library, and PAV will be able to find it through that.

**Comment by harris-2374** [comment]
When I originally installed PAV, I did so through the recursive clone, so svpop and kanapy were included. I have tried to re-clone the repository and give it another go with the latest commit, but I am now running into the same issue presented in #16.

**Comment by paudano** [comment]
Can you tell me what version of Snakemake you are running? It should be filling in those wildcards. I might need to switch that to an input function. I might be on an older version on Snakemake and not seeing this problem yet.

**Comment by harris-2374** [comment]
Ah! I was on a very old version of Snakemake... v3.13.3. This could just be an issue on my end, but there appears to be minor incompatibilities between a few dependencies that caused Conda to downgrade packages until the incompatibilities went away (e.g., down to v3.13.3). This happened when I installed all dependencies in one command. To fix this, I had to create a new environment and install Snakemake (v7.12.0) first, then install the rest of the dependencies separately. This resolved the issue noted in #16 for me, but I am still having issues with the inversion figures not generating. I no longer receive the error about failing to import kanapy (small win?), but it now says it can't import Biopython (I double-checked it was actually installed and it is). I've attached the new error below. 

[inv_call_1.log](https://github.com/EichlerLab/pav/files/9254993/inv_call_1.log)

**Comment by paudano** [comment]
I can't imagine why it wouldn't find Biopython. Have you been able to resolve this since? I do need to dockerize this, hopefully that will solve some of these dependency and library problems.

**Comment by harris-2374** [comment]
Unfortunately, I have not. If you get PAV into a Docker container, I will try it out and see if I still end up with the error. Thanks for the help!

**Comment by paudano** [comment]
Dockerized version of PAV (and singularity image) should be ready soon. Sorry for the delays.

**Comment by paudano** [comment]
PAV is now on Docker and Singularity. See README.md for instructions.
