### ISSUE TITLE
Bug in parsing the contig name

### ISSUE THREAD

**Issue by LYC-vio** [EichlerLab/pav#18]
I'm sorry that the error log has been overwritten, but I did notice that the format of the contig name will cause strange bugs in PAV

PAV will raise errors if the contig names are all numbers. eg:
```
>100240
``` 
this can be fixed by adding characters/letters, eg:
```
>ctg100240
```

**Comment by paudano** [comment]
I'll test and fix this, thank you for reporting and my apologies for the slow response.

**Comment by paudano** [comment]
I merged the fix from @PengJia6 (Thanks!). I'll test with some other bug fixes I am working on now and should release a new version soon.
