### ISSUE TITLE
Unable to read in FASTA

### ISSUE THREAD

**Issue by damioresegun** [EichlerLab/pav#2]
Hi,
After setting up the tool as per instructions, I am getting the error below. 
I am using assemblies.tsv approach with the assemblies.tsv AND config.json in the current directory where the output will be written to. 
The kanapy is in the actual pav master folder and a soft link to analib is also in the pav master folder. 
Command used: `snakemake -s /home/doresegu/scratch/apps/PAV_SV/pav/Snakefile --cores 32`

Config.json looks like this:
`{
        "reference": "/home/doresegu/scratch/private/Analysis/NewGenomes/Cultured.fasta",
        "assembly_table": "/home/doresegu/scratch/private/Analysis/PAV_SV/assemblies.tsv"
}`

Assemblies.tsv looks like this:
NAME  HAP1      HAP2
sks047  /home/doresegu/scratch/private/Analysis/NewGenomes/sks047.fasta
sks048  /home/doresegu/scratch/private/Analysis/NewGenomes/sks048.fasta

Error message: `Building DAG of jobs...
WorkflowError in line 483 of /home/doresegu/scratch/apps/PAV_SV/pav/rules/align.snakefile:
Function did not return str or list of str.`

I have looked in the specified rule and all it is doing is stating the function. I'm not sure how to proceed. I have also tried with .gz of the fasta files

Thanks

**Comment by paudano** [comment]
When in input function fails, Snakemake drops the trace, so you never see the real error message. However, I think you provided enough information to see the error.

assemblies.tsv is a TSV file with three columns, but yours has only two; "NAME" and "HAP1" have values, but "HAP2" does not. If "sks047" and "sks048" are not phased assemblies (one FASTA for the sample), then create an empty file (0 bytes) and add a path to that empty file as HAP2 for both samples.

**Comment by damioresegun** [comment]
Ahh I see. I got it to read in the FASTA but now its not going past the alignment phase. It really isnt telling me much. Could you have a look at the attached log file please?

[2021-01-28T113907.961432.snakemake.log](https://github.com/EichlerLab/pav/files/5886830/2021-01-28T113907.961432.snakemake.log)

**Comment by paudano** [comment]
I just realized this issue was sitting here. Are you still trying to run PAV, and have you gotten past the error? Generally, PAV writes pretty good error messages, but I don't see any in the log. It doesn't look like it was sent out to a cluster either, so the log wouldn't be in a cluster log, would it?
