### ISSUE TITLE
CIGAR parsing error: Bad CIGAR op: N 

### ISSUE THREAD

**Issue by zou-yawen** [EichlerLab/pav#21]
hi,when I use pav ,I meet a problem below:"CIGAR parsing error: Bad CIGAR op: N (INDEX=130, QUERY=chr1, LOC=chr1:16557928-103704932)"   the cigar string is 253843626S87147004N.The error pos  is here 
![image](https://user-images.githubusercontent.com/72124697/188909404-352d7513-5f7f-43fd-94ab-a27f2e92e349.png)
Can give me some advice to solve it

**Comment by paudano** [comment]
An "N" CIGAR op should not be in the contig alignments, it's typically used for transcript alignments over introns. Did you use the alignments built into PAV or push in your own alignments?

**Comment by zou-yawen** [comment]
Sorry,it`s my problem; I  added an extra parameter  '-L '  in minimap2 accidentally when adjusting the code.Thank you very much

**Comment by paudano** [comment]
Thanks, that's useful information!
