### ISSUE TITLE
keeping temp file option for singularity run

### ISSUE THREAD

**Issue by bioinfogit** [EichlerLab/pav#29]
Hi 
How can I  keep temp file to then end of the run while running with singularity?

Bw

**Comment by bioinfogit** [comment]
then*=the

**Comment by paudano** [comment]
Add "--nt" to the command-line to instruct the pipeline to leave temp files after it is done with them. All files marked as temporary are written to the `temp` directory, so all temp files can be removed by deleting the `temp` directory when you are ready to clear them.

For example:
`singularity run --bind "$(pwd):$(pwd)" --writable-tmpfs library://becklab/pav/pav:latest --cores 12 --nt`

Any Snakemake options, like `--nt`, can be appended to control the workflow or request specific files be generated (e.g. Can run specific samples or run up to a step and stop).

Let me know if this helps.

**Comment by bioinfogit** [comment]
Dear Peter 

thanks for this. yes it was very helpful 

Bw
