### ISSUE TITLE
module ‘analib.pd’ has no attribute 'read_csv_chrom'

### ISSUE THREAD

**Issue by PengJia6** [EichlerLab/pav#3]
Hi, 

Thanks for developing such an excellent pipeline! 

I found the [asmlib.call.merge_haplotypes](https://github.com/EichlerLab/pav/blob/master/rules/call.snakefile#L147) function in rule call_merge_haplotypes was errored because the missing of [read_csv_chrom](https://github.com/EichlerLab/pav/blob/master/asmlib/call.py/#L171) in analib.pd.  

I used the lastest verision of analib in svpop.

Best,
Peng Jia

**Comment by paudano** [comment]
The version of PAV is out of sync with SV-Pop in the `dep` directory. `analib.pd.read_csv_chrom()` (in SV-Pop) is a newer function that PAV expects. I need to make the dependencies into a submodule to keep them in sync. I'll let you know when that's done, then you can pull a new version of PAV and run it.

**Comment by PengJia6** [comment]
Thanks a lot! 
Best,
Peng

**Comment by PengJia6** [comment]
Thanks for your reminder! I look forward to seeing the new update! 

BTW, pav provides 2 aligner (lra and minimap2) for contig mapping, which one do you recommend?

**Comment by paudano** [comment]
Those dependencies (kanapy and SV-Pop) are now submodules:

`git clone --recursive https://github.com/EichlerLab/pav.git`

That should take care of the problem you were having.

See `README.md` for other Python and external dependencies.

There are some other fixes in this, which took some time to test. Thank you for your patience!
