### ISSUE TITLE
Detecion of DUP and BND

### ISSUE THREAD

**Issue by jyw-atgithub** [EichlerLab/pav#33]
Dear authors, 
May I know if the PAV is capable of detecting duplications (DUP) and translocations (BND) from an unphased assembly now or in the future? 
Thank you!

**Comment by paudano** [comment]
Duplication calls (DUP) are insertions that are not fully resolved. Instead, PAV will detect an insertion (INS). DUP tells you which locus was duplication, INS tells you where it landed and what the actual sequence of the duplication is (i.e. small differences between the inserted and reference copies). To translate INS to DUP, I typically align INS sequences back to the reference and see if I can tell where they came from. PAV writes INS sequences to a FASTA file (results/ASM_NAME/bed/fa), and you can just align those to the reference with minimap2. There are some issues correctly attaching INS to duplicated regions this way, particularly for tandem duplications, and I am working to improve that. Someday, I'd like to have PAV write both the INS call along with a likely duplicated template region in reference space.

Translocations are not currently called by PAV, but it is high on my list of improvements. When I developed PAV for HGSVC, we did not have known translocations, and so calling them without QC'ing the method was too risky. This is an improvement I hope to make in the near future.

Let me know if this helps.

**Comment by jyw-atgithub** [comment]
Hi, Peter! 
Thank you so much for the detailed explination! I will try this method.

**Comment by paudano** [comment]
Great! I'll close this for now, but open the case again if you have other questions about it.
