### ISSUE TITLE
Error in json file format

### ISSUE THREAD

**Issue by priyambial123** [EichlerLab/pav#38]
Hello,

I am using singularity to run the analysis. This is the json file:

```
{
  "reference": "/reference/human_GRCh38_no_alt_analysis_set.fasta",
  "asm_pattern": "/samples/002-020-secondcleanup/aligned/{002-020-secondcleanup.asm.bp}/{hap.p_ctg}.fasta.gz"
}  
```

config.json and assemblies are in the same folder. Using this folder as the current directory and executed the code:

`singularity run --bind "$(pwd):$(pwd)" library://becklab/pav/pav:2.2.7 -c 16`

Then I got this output:

```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 16
Rules claiming more threads will be scaled down.
Job stats:
job        count    min threads    max threads
-------  -------  -------------  -------------
pav_all        1              1              1
total          1              1              1

Select jobs to execute...

[Thu Jun  8 12:30:42 2023]
localrule pav_all:
    jobid: 0
    reason: Rules with neither input nor output files are always executed.
    resources: tmpdir=/dev/shm/tmp

[Thu Jun  8 12:30:42 2023]
Finished job 0.
1 of 1 steps (100%) done
```
Is the error is due to the file name in the config.json?. I tried editing the file name several times but I get the same output as above. 

Thank you

**Comment by paudano** [comment]
If you are using `asm_pattern` to find assemblies, then you'll need to specify which files you want to output. This is a feature most would not use. Based on the pattern, it looks like you put "002-020-secondcleanup.asm.bp" in place of the "sample" wildcard. Is that the sample you are using? If so, just create an `assemblies.tsv` file with that as the name ("NAME" column) and the full path to the assembly ("HAP1" column, remove the braces from the path), then run it that way. PAV will use the list of samples in `assemblies.tsv` and run them all.

**Comment by paudano** [comment]
Let me know if you were able to get it running or if you need additional help.

**Comment by priyambial123** [comment]
I gave the reference path in config json file:

{
  "reference": /GROUP/pav/hg38_no_alt/hg38.no_alt.fa.gz"
}


 and path to the assemblies in tsv file with Name and HAP1 and HAP2 columns

The input reference file is missing. I run it from the path of config.json and assemblies.tsv file. 

```
singularity run --bind "$(pwd):$(pwd)" library://becklab/pav/pav:2.2.7 -c 16
INFO:    Using cached image
Building DAG of jobs...
MissingInputException in rule data_align_ref  in line 85 of /opt/pav/rules/data.snakefile:
Missing input files for rule data_align_ref:
    output: data/ref/ref.fa.gz, data/ref/ref.fa.gz.fai
    affected files:
        /pav/hg38_no_alt/hg38.no_alt.fa.gz
```

**Comment by priyambial123** [comment]
Thank you. I could start running the analysis but it has stopped with an error in the align_get_read_bed step. Can you help to find the issue here

```
rule align_get_read_bed:
    input: temp/0012-001/align/pre-cut/aligned_tig_h1.sam.gz, temp/0012-001/align/contigs_h1.fa.gz.fai
    output: results/0012-001/align/pre-cut/aligned_tig_h1.bed.gz, results/0012-001/align/pre-cut/aligned_tig_h1.headers.gz
    jobid: 11
    reason: Missing output files: results/0012-001/align/pre-cut/aligned_tig_h1.bed.gz
    wildcards: asm_name=0012-001, hap=h1
    resources: tmpdir=/dev/shm/tmp

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 16
Rules claiming more threads will be scaled down.
Select jobs to execute...
[E::inflate_gzip_block] Gzip file truncated
[E::bgzf_read_block] Reading GZIP stream failed at offset 3112960
[W::sam_read1_sam] Parse error at line 1192
[Tue Jul  4 11:49:49 2023]
Error in rule align_get_read_bed:
    jobid: 0
    input: temp/0012-001/align/pre-cut/aligned_tig_h1.sam.gz, temp/0012-001/align/contigs_h1.fa.gz.fai
    output: results/0012-001/align/pre-cut/aligned_tig_h1.bed.gz, results/0012-001/align/pre-cut/aligned_tig_h1.headers.gz



```

**Comment by paudano** [comment]
My appologies, I just saw your response.

Looks like `temp/0012-001/align/pre-cut/aligned_tig_h1.sam.gz` is a partial truncated file. The error says `[E::inflate_gzip_block] Gzip file truncated`, and that's the gzipped file it's trying to read.
