### ISSUE TITLE
job suspend with no error information

### ISSUE THREAD

**Issue by leon945945** [EichlerLab/pav#39]
Hi, I'm using PAV to call variantion, but the program suspended with no information for over 10 hours, was that normal?

Here are the log file:

> Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 80
Rules claiming more threads will be scaled down.
Select jobs to execute...
INV Found: outer=h2tg000333l:157572-164831, inner=h2tg000333l:157572-164831 (ref outer=h2tg000018l:23093692-23101248, inner=h2tg000018l:23093692-23101248)
INV Found: outer=h2tg000081l:1070997-1123757, inner=h2tg000081l:1070997-1123757 (ref outer=h2tg000031l:359077-431125, inner=h2tg000031l:359077-431125)
[Tue Aug 12 11:03:23 2003]
Finished job 130.
531 of 845 steps (63%) done
[Tue Aug 12 11:05:20 2003]
Finished job 589.
532 of 845 steps (63%) done
INV Found: outer=h2tg000170l:305920-319882, inner=h2tg000170l:305920-319882 (ref outer=h2tg000032l:3949760-3950667, inner=h2tg000032l:3949760-3950667)
INV Found: outer=h2tg000170l:305727-319882, inner=h2tg000170l:305727-319882 (ref outer=h2tg000032l:3949559-3950667, inner=h2tg000032l:3949559-3950667)
[Tue Aug 12 11:06:27 2003]
Finished job 122.
533 of 845 steps (63%) done
[Tue Aug 12 11:13:59 2003]
Finished job 124.
534 of 845 steps (63%) done
[Tue Aug 12 11:17:22 2003]
Finished job 128.
535 of 845 steps (63%) done

And the time now is `Tue Aug 12 23:53:28 CST 2003`

When I use `top` to see whether PAV was running, no programs were running, so I think it's abnormal.

**Comment by leon945945** [comment]
Actually, there are rule exceptions:

> RuleException:
RuntimeError in file /home/songlizhi/software/pav/rules/call_lg.snakefile, line 79:
Received return code 1 from scripts/density.py for region h2tg000061l:2936243-3361038:
OpenBLAS blas_thread_init: pthread_create failed for thread 15 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 16 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 17 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 18 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 19 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 20 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 21 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 22 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 23 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 24 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 25 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 26 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 27 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 28 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 29 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 30 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 31 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 32 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 33 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 34 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 35 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 36 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 37 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 38 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 39 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 40 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 41 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 42 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 43 of 80: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2062946 max
OpenBLAS blas_thread_init: pthread_create failed for thread 44 of 80: Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/songlizhi/software/pav/scripts/density.py", line 557, in <module>
    get_smoothed_density()
  File "/home/songlizhi/software/pav/scripts/density.py", line 289, in get_smoothed_density
    pool = mp.Pool(threads, initializer=init_process)
  File "/home/songlizhi/software/miniconda3/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/home/songlizhi/software/miniconda3/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/home/songlizhi/software/miniconda3/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/home/songlizhi/software/miniconda3/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/home/songlizhi/software/miniconda3/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/songlizhi/software/miniconda3/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/songlizhi/software/miniconda3/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/songlizhi/software/miniconda3/lib/python3.9/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable

  File "/home/songlizhi/software/pav/rules/call_lg.snakefile", line 79, in __rule_call_lg_discover
  File "/home/songlizhi/software/pav/pavlib/lgsv.py", line 309, in scan_for_events
  File "/home/songlizhi/software/pav/pavlib/inv.py", line 278, in scan_for_inv
  File "/home/songlizhi/software/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

No idea what's wrong.

**Comment by paudano** [comment]
Try `export OPENBLAS_NUM_THREADS=1` on the command-line before running PAV. There could be a conflict with thread managers, and I think this might solve it.

This can also be caused by a limit on the number of threads a process can create. It is common for administrators to set such a limit on cluster head nodes, but I'm not sure where else you would encounter it. If you are on a cluster, is this being run in a compute node? I think this is something you'll have to take up with the system administrators, ask why there's a thread limit and if PAV is being run in the right compute environment. You can try setting the thread limit on the shell before starting PAV (i.e.`ulimit -u 10000`), but I don't expect that to work.

Let me know what OPENBLAS_NUM_THREADS does. If that works, I can see if making PAV set that automatically makes sense for most environments.

**Comment by leon945945** [comment]
Hi, I tried `export OPENBLAS_NUM_THREADS=1` before running PAV, and PAV ran successfully.
Here are the logs:

> [Wed Aug 13 19:40:24 2003]
Finished job 0.
845 of 845 steps (100%) done
Complete log: .snakemake/log/2003-08-13T125359.377909.snakemake.log

Meanwhile I want to know what does the "Missing output files" mean in log file? Does it influence the program running or results?

> [Wed Aug 13 19:10:47 2003]
rule call_final_bed:
    input: temp/YFGX/bed/merged/svindel_ins.bed.gz, temp/YFGX/bed/merged/svindel_del.bed.gz, temp/YFGX/bed/merged/sv_inv.bed.gz, temp/YFGX/bed/merged/snv_snv.bed.gz
    output: results/YFGX/bed/snv_snv.bed.gz, results/YFGX/bed/indel_ins.bed.gz, results/YFGX/bed/indel_del.bed.gz, results/YFGX/bed/sv_ins.bed.gz, results/YFGX/bed/sv_del.bed.gz, results/YFGX/bed/sv_inv.bed.gz, results/YFGX/bed/fa/indel_ins.fa.gz, results/YFGX/bed/fa/indel_del.fa.gz, results/YFGX/bed/fa/sv_ins.fa.gz, results/YFGX/bed/fa/sv_del.fa.gz, results/YFGX/bed/fa/sv_inv.fa.gz
    jobid: 566
    reason: **Missing output files**: results/YFGX/bed/fa/indel_ins.fa.gz, results/YFGX/bed/sv_ins.bed.gz, results/YFGX/bed/sv_inv.bed.gz, results/YFGX/bed/fa/sv_del.fa.gz, results/YFGX/bed/indel_del.bed.gz, results/YFGX/bed/indel_ins.bed.gz, results/YFGX/bed/sv_del.bed.gz, results/YFGX/bed/snv_snv.bed.gz, results/YFGX/bed/fa/indel_del.fa.gz, results/YFGX/bed/fa/sv_ins.fa.gz, results/YFGX/bed/fa/sv_inv.fa.gz; Input files updated by another job: temp/YFGX/bed/merged/snv_snv.bed.gz, temp/YFGX/bed/merged/svindel_ins.bed.gz, temp/YFGX/bed/merged/svindel_del.bed.gz, temp/YFGX/bed/merged/sv_inv.bed.gz
    wildcards: asm_name=YFGX
    resources: tmpdir=/tmp

Thank you very much.

**Comment by paudano** [comment]
PAV is run by Snakemake to manage the whole workflow. That's why PAV can pick up where it left off if you resume an interrupted run. The "reason:" is Snakemake telling why it's running a step (a "rule"). It could run it because the output file the rule generates is missing (i.e. "Missing output files") or another reason like a file it depends on was updated and the rule needs to be re-run. If Snakemake workflows start re-running rules unexpectedly, this line is helpful for determining why.

I am turning this into an enhancement for now. I have some hard deadlines this week, then I want to see if it makes sense to have this option set by the pipeline (need to make sure it won't cause problems in other environments). I don't need anything else unless you want to test it later.

Thank you for the feedback, it should help others run PAV!

**Comment by leon945945** [comment]
I'm very glad to make a little bit contribution to PAV development.

**Comment by paudano** [comment]
I think setting `OPENBLAS_NUM_THREADS=1` by default for everyone is risky, but I did add it to the documentation for native PAV installs. If this issues comes up in the containerized versions of PAV we distribute, I'll re-open and look into it.

Thanks again for the report.
