### ISSUE TITLE
insertion and deletion from different chromosome

### ISSUE THREAD

**Issue by chycheng2015** [EichlerLab/pav#43]
Hi,

I tried to found SVs in a phased assembly genome of HG002, and found some insertion and deletion corresponding to ref (GRCh37) are from different chromosom. For example, an ins on chr1-34044-34045 are from paternal's chr12-21613-24633. How do you explain this?

**Comment by paudano** [comment]
It's hard to know without more specific details. 3 kbp is about the size of a human LINE, are you seeing a LINE insertion in one place and the absence of a reference LINE in another? Are the variants in segmental duplications. See what's at the locations in the UCSC browser (turn on "Segmental Dups", "RepeatMasker", and TRF tracks).
