### ISSUE TITLE
Program mysteriously exited without any error message

### ISSUE THREAD

**Issue by WeiYang-BAI** [EichlerLab/pav#5]
Hi everyone,

My job exited without any error message, which is quite unusual. I tried many times and everytime the most far I can go is the 7 step. The config.json and complete log is pasted below, could anyone give me a hint please?

json file:
{
  "reference": "/my-path/human_referene_gemone/GRCh38.no_alt/hg38.no_alt.fa",
  "asm_pattern": "/my-path/{asm_name}/{hap}.fa.gz"
}

log file:
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 12
Rules claiming more threads will be scaled down.
Job stats:
job                             count    min threads    max threads
----------------------------  -------  -------------  -------------
align_cut_tig_overlap               2              1              1
align_get_read_bed                  2              1              1
align_get_tig_fa                    2              1              1
align_map                           2              1              1
align_ref                           1              1              1
align_ref_anno_n_gap                1              1              1
call_cigar                         20              1              1
call_cigar_merge                    2              1              1
call_final_bed                      1              1              1
call_integrate_sources              2              1              1
call_inv_batch                    120              1              1
call_inv_batch_merge                2              1              1
call_inv_cluster                    4              1              1
call_inv_flag_insdel_cluster        4              1              1
call_inv_merge_flagged_loci         2              1              1
call_lg_discover                   20              1              1
call_lg_split                       2              1              1
call_mappable_bed                   2              1              1
call_merge_haplotypes               4              1              1
call_merge_haplotypes_chrom       776              1              1
call_merge_lg                       6              1              1
data_ref_contig_table               1              1              1
vcf_write_vcf                       1              1              1
total                             979              1              1

Select jobs to execute...

[Fri Sep 10 16:46:26 2021]
rule data_ref_contig_table:
    output: data/ref/contig_info.tsv.gz
    jobid: 978
    resources: tmpdir=/tmp

[Fri Sep 10 16:46:26 2021]
rule align_get_tig_fa:
    input: /my-path/NA21309/h2.fa.gz
    output: temp/NA21309/align/contigs_h2.fa.gz, temp/NA21309/align/contigs_h2.fa.gz.fai
    jobid: 107
    wildcards: asm_name=NA21309, hap=h2
    resources: tmpdir=/tmp

[Fri Sep 10 16:46:26 2021]
rule align_get_tig_fa:
    input: /my-path/NA21309/h1.fa.gz
    output: temp/NA21309/align/contigs_h1.fa.gz, temp/NA21309/align/contigs_h1.fa.gz.fai
    jobid: 10
    wildcards: asm_name=NA21309, hap=h1
    resources: tmpdir=/tmp

[Fri Sep 10 16:46:26 2021]
rule align_ref:
    input: /my-path/human_referene_gemone/GRCh38.no_alt/hg38.no_alt.fa
    output: data/ref/ref.fa.gz, data/ref/ref.fa.gz.fai
    jobid: 9
    resources: tmpdir=/tmp

[Fri Sep 10 16:46:48 2021]
Finished job 978.
1 of 979 steps (0.1%) done
[Fri Sep 10 16:55:38 2021]
Finished job 9.
2 of 979 steps (0.2%) done
Select jobs to execute...

[Fri Sep 10 16:55:38 2021]
rule align_ref_anno_n_gap:
    input: data/ref/ref.fa.gz
    output: data/ref/n_gap.bed.gz
    jobid: 23
    resources: tmpdir=/tmp

[Fri Sep 10 16:55:48 2021]
Finished job 10.
3 of 979 steps (0.3%) done
Select jobs to execute...

[Fri Sep 10 16:55:48 2021]
rule align_map:
    input: data/ref/ref.fa.gz, temp/NA21309/align/contigs_h1.fa.gz
    output: temp/NA21309/align/pre-cut/aligned_tig_h1.sam.gz
    jobid: 8
    wildcards: asm_name=NA21309, hap=h1
    resources: tmpdir=/tmp

[Fri Sep 10 16:55:50 2021]
Finished job 107.
4 of 979 steps (0.4%) done
Select jobs to execute...

[Fri Sep 10 16:55:50 2021]
rule align_map:
    input: data/ref/ref.fa.gz, temp/NA21309/align/contigs_h2.fa.gz
    output: temp/NA21309/align/pre-cut/aligned_tig_h2.sam.gz
    jobid: 106
    wildcards: asm_name=NA21309, hap=h2
    resources: tmpdir=/tmp

[Fri Sep 10 16:59:41 2021]
Finished job 23.
5 of 979 steps (1%) done
[Fri Sep 10 17:04:33 2021]
Finished job 8.
6 of 979 steps (1%) done
Select jobs to execute...

[Fri Sep 10 17:04:33 2021]
rule align_get_read_bed:
    input: temp/NA21309/align/pre-cut/aligned_tig_h1.sam.gz, temp/NA21309/align/contigs_h1.fa.gz.fai
    output: results/NA21309/align/pre-cut/aligned_tig_h1.bed.gz, results/NA21309/align/pre-cut/aligned_tig_h1.headers.gz
    jobid: 7
    wildcards: asm_name=NA21309, hap=h1
    resources: tmpdir=/tmp

[Fri Sep 10 17:05:33 2021]
Finished job 106.
7 of 979 steps (1%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by paudano** [comment]
By tracing the job IDs, it looks like it's failing on this step:

```
[Fri Sep 10 17:04:33 2021]
rule align_get_read_bed:
input: temp/NA21309/align/pre-cut/aligned_tig_h1.sam.gz, temp/NA21309/align/contigs_h1.fa.gz.fai
output: results/NA21309/align/pre-cut/aligned_tig_h1.bed.gz, results/NA21309/align/pre-cut/aligned_tig_h1.headers.gz
jobid: 7
wildcards: asm_name=NA21309, hap=h1
resources: tmpdir=/tmp
```

This rule is the first to use pysam, and I have had problems with pysam 0.16 crashing (0.15.2 works, see #4, Comments on June 18).

I'm not sure why Snakemake isn't giving you an error to the screen that the rule is failing. The only thing I can think of is `onerror` handler that might send the message somewhere else, but PAV doesn't use `onerror`. If you output to a log file, then check the log for job 7, and it might have segmentation fault from pysam. If you can change your pysam version in the Python distribution you are using, that will likely solve the problem. If it doesn't or if you find the error output (depends on the cluster or how Snakemake is run), then please post that.

Please let me know if this helps.

**Comment by WeiYang-BAI** [comment]
Hi  paudano,

Sorry for the late reply, I replaced pysam 0.16 with the 0.15.2 (and 0.15.3 also) in python3.8.5, the job, however, still exited when 7 steps were done. The cluster and snakemake did not give any error output. Thanks for your help anyway, I will try more, like different python distributions, and post infos if I go any further.

**Comment by WeiYang-BAI** [comment]
Hi paudano,

I tried python 3.5-3.9 (with default distribuations in conda ), the job finally worked in 3.8.6 with pysam 0.15.2. 

I slightly suspect that the program aborted unexpectedly may caused by both pysam version and its dependency in python. For me, the pysam 0.15.2 works pretty well with python 3.8.6 but not with other distribuations. Also, some of them showed the dependency conflicts when installing the package.

Still, I don't know why the cluster and snakemake didn't  capture error message and throw it out, this is quit cryptic.

**Comment by WeiYang-BAI** [comment]
Thanks for your help again!

**Comment by paudano** [comment]
Thanks for sharing what worked for you. I haven't had these kinds of problems with the Python environment yet, but if enough people do, I'll consider releasing a Conda env or Singularity image.

**Comment by leleory** [comment]
Hi Paudano,
I have the same problem as WeiYang. After the step align_get_read_bed finished successfully, the step align_cut_tig_overlap fails, without reporting any errors.
This happens with various python and pysam versions. I have tested with WeiYang's suggestions of python 3.8.6 and pysam 0.15.2 and with others (python 3.10.4 & pysam 0.19.1, python 3.9.13 & pysam 0.9.1).

Can you suggest ways to test for errors in the align_cut_tig_overlap module?

Also, do you have suggestions for python and pysam versions which should run OK?

Thanks, Lel

The tail of the log is below:
[Mon Jun 13 08:51:34 2022]
rule align_get_read_bed:
    input: temp/bj/align/pre-cut/aligned_tig_h1.sam.gz, temp/bj/align/contigs_h1.fa.gz.fai
    output: results/bj/align/pre-cut/aligned_tig_h1.bed.gz, results/bj/align/pre-cut/aligned_tig_h1.headers.gz
    jobid: 7
    reason: Missing output files: results/bj/align/pre-cut/aligned_tig_h1.bed.gz; Input files updated by another job: temp/bj/align/contigs_h1.fa.gz.fai, temp/bj/align/pre-cut/aligned_tig_h1.sam.gz
    wildcards: asm_name=bj, hap=h1
    resources: tmpdir=/exports/eddie/scratch/leory2

/exports/cmvm/eddie/eb/groups/archibald_bioinf/src/pav/dep/svpop/svpoplib/ref.py:121: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  return pd.read_csv(
[Mon Jun 13 08:51:43 2022]
Finished job 7.
6 of 207 steps (3%) done
Removing temporary output temp/bj/align/pre-cut/aligned_tig_h1.sam.gz.
Select jobs to execute...

[Mon Jun 13 08:51:43 2022]
rule align_cut_tig_overlap:
    input: results/bj/align/pre-cut/aligned_tig_h1.bed.gz, temp/bj/align/contigs_h1.fa.gz.fai
    output: results/bj/align/aligned_tig_h1.bed.gz
    jobid: 6
    reason: Missing output files: results/bj/align/aligned_tig_h1.bed.gz; Input files updated by another job: temp/bj/align/contigs_h1.fa.gz.fai, results/bj/align/pre-cut/aligned_tig_h1.bed.gz
    wildcards: asm_name=bj, hap=h1
    resources: tmpdir=/exports/eddie/scratch/leory2

/exports/cmvm/eddie/eb/groups/archibald_bioinf/src/pav/dep/svpop/svpoplib/ref.py:121: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  return pd.read_csv(
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-06-13T084911.233781.snakemake.log
