### ISSUE TITLE
Can PAV works in high het organisms?

### ISSUE THREAD

**Issue by Axze-rgb** [EichlerLab/pav#51]
Hello, 

My organism has a heterozygosity of a few percents, so we see a snp every 30 bases. Since the human genome has a snp every 1000 bases, I was wondering if PAV has expectations regarding high het. Will it penalizes variants because because they are too close to one another? 

Thanks

**Comment by paudano** [comment]
PAV does not assume any model of variation, so it should work well as long as the assembly alignments work. By default, it uses minimap parameter `-x asm20` (with other parameters), which assumes 5% divergence from the reference. The default options might work (SNP every 30 bp is 3% divergence), but parameters can be adjusted if needed.
