### ISSUE TITLE
Strange number of SVs from PAV2.3.4

### ISSUE THREAD

**Issue by yangsui0122** [EichlerLab/pav#53]
Hi Peter,
We ran PAV for some autism samples, and found some weird results.
We have evaluated the stats of assemblies (from hifiasm-trio), and all of them look good, for example,
```
read_cov_X	read_n50_kbp	HiFi-aln_GRCh38_DP	asm_n50_hap1	asm_n50_hap2	asm_qv_hap1	asm_qv_hap2	contigCt_hap1	contigCt_hap2	contigGbp_hap1	contigGbp_hap2	sample
33.507	19.3	33.5524	31.7	38.24	53.322	52.8952	883	851	2.979	2.987	12237_p1
```
We initially found 15 samples have weird VCF results, including too few SVs (18,000, >=50bp) compared to an average of 27,000, and wrong GT of either "1|." or "1|1" for all records in VCF. I have checked the intermediate cram file in the align output folder in IGV, some het variants can be seen in the cram in IGV but not in the VCF (and also called by PBSV).
 
After re-running those 15 samples for 3 times, we have solved 14 samples by using exactly the same environment (Ubuntu and etc), PAV2.3.4 and input, we don't know why and how we solved those 14 samples. But not for one sample, 12237_p1, I can see the numbers of SVs are similar (17927, 17983, 17983), and all the GTs are "1|.".

Could you please help us with this issue? and please feel free to let me know if you need any assemblies and VCFs~

Thanks,
Yang

**Comment by paudano** [comment]
If all the GTs are "1|.", then a haplotype 2 is missing. Can you look at the configuration and make sure haplotype 2 for that sample points to a valid assembly file with data in it?

**Comment by yangsui0122** [comment]
Thank you, you are right, sorry, I saw the hap2 is empty~ Will double check the manifest. Sorry and thanks~

**Comment by paudano** [comment]
Sure, no problem. I'll close this, but re-open if something isn't right.
