### ISSUE TITLE
snakefile is using a wrong python version

### ISSUE THREAD

**Issue by WeiCSong** [EichlerLab/pav#55]
Hi, 
when using localrun, i found that the snakefile used python 3.12 that is not in the current enviroment and caused version conflict with numpy:

> ImportError in file /lustre/home/acct-bioxsyy/bioxsyy-user2/pav-2.3.4/Snakefile, line 15:
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:
 https://numpy.org/devdocs/user/troubleshooting-importerror.html
Please note and check the following:
The Python version is: Python3.12 from "/lustre/opt/cascadelake/linux-rhel8-skylake_avx512/gcc-8.5.0/miniconda3-24.3.0-3zpg/bin/python"
 The NumPy version is: "1.19.5"

I added 
`shell.prefix("source activate pacbio; ")
shell.executable("/lustre/home/myaccount/.conda/envs/pacbio/bin/python")`

to the snakefile, and manually set ENV_FILE=None in the snakefile, but it still used the wrong python 3.12 outside my enviroment. Is there any config option i  missed that set the enviroment and path automatically? Thanks for your help.

**Comment by paudano** [comment]
Snakemake doesn't run Python code as shell commands, that will inherit the Python version in the environment were PAV is launched. If `which python` or `which python3` points to the right executable before launching PAV, then it should be running in the correct environment. The `shell.prefix` will prepend that text to the beginning of any shell rules, but most of PAV is in "run" rules, which used the Python environment the Snakemake process was launched in.

**Comment by paudano** [comment]
Were you able to get PAV to run? Let me know if I can help further.

**Comment by WeiCSong** [comment]
Thanks for the information! I changed the enviroment that have correct version in which python and pav could work
