### ISSUE TITLE
could not download example data

### ISSUE THREAD

**Issue by jeffchen2000** [EichlerLab/pav#57]
I could not download example data, is there an alternative way?
thanks

 wget ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/HGSVC2/working/20221202_PAV_Example/* -P assemblies/
--2024-09-18 11:36:32--  ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/HGSVC2/working/20221202_PAV_Example/*
           => ‘assemblies/.listing’
Resolving ftp.1000genomes.ebi.ac.uk (ftp.1000genomes.ebi.ac.uk)... 193.62.193.167
Connecting to ftp.1000genomes.ebi.ac.uk (ftp.1000genomes.ebi.ac.uk)|193.62.193.167|:21... connected.
Logging in as anonymous ...
Login incorrect.

**Comment by paudano** [comment]
It might have been a temporary glitch on the FTP machine. The command works for me. Can you try it again?

**Comment by jeffchen2000** [comment]
worked--thank you !
