### ISSUE TITLE
maybe a bug in call.snakefile

### ISSUE THREAD

**Issue by PengJia6** [EichlerLab/pav#7]
https://github.com/EichlerLab/pav/blob/a9a15b9c61222c4f60f22eb1352d562466b7410c/rules/call.snakefile#L352

I need to changed this line to 
```
lambda row: len(filter_tree[row['#CHROM']][row['POS']:row['END']]) == 0,

 ```
in my PAV run.

**Comment by paudano** [comment]
I about to push an update, and this code changed quite a bit. I verified this bug was fixed in those changes. Thank you for reporting this.
