### ISSUE TITLE
toy example with code

### ISSUE THREAD

**Issue by leleory** [EichlerLab/pav#9]
Hi,
Can you please add a small toy example to the source, so the install can be tested?
Having in place both data and correctly set-up config files would help defining whether a potential error was caused by a wrong install or by an error in custom data/config files.
Also, having a correct set of log files after a successful run on the toy example would help to understand what job is failing and what should be the correct output.
Thanks,
Lel

**Comment by paudano** [comment]
I think this is a good idea, and I'll include it with the next major release (still working on some updates).

**Comment by paudano** [comment]
I have now included a small example in version 2.2.0.
